# Generated by Django 4.2.7 on 2023-11-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id_avis', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('commentaire', models.CharField(max_length=200)),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Frigo',
            fields=[
                ('id_frigo', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id_ingredient', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nom_ingredient', models.CharField(max_length=50)),
                ('unite', models.CharField(max_length=50)),
                ('id_frigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.frigo')),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id_recette', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nom_recette', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=200)),
                ('popularite', models.IntegerField(default=0)),
                ('temps_preparation', models.IntegerField(default=0)),
                ('temps_cuisson', models.IntegerField(default=0)),
                ('id_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=10)),
                ('origine', models.CharField(max_length=20)),
                ('id_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.recette')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_plat',
            fields=[
                ('id_photo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('chemin_photo', models.ImageField(upload_to='media/photo_plat')),
                ('id_avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.avis')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.service')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='frigo',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.utilisateur'),
        ),
        migrations.AddField(
            model_name='avis',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.service'),
        ),
        migrations.AddField(
            model_name='avis',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuisine_IPW.utilisateur'),
        ),
    ]
